"""
工作流错误码枚举

定义工作流模块所有错误码，用于前后端错误消息国际化。
前端根据 error_code 映射到对应的翻译键。
"""

from enum import Enum


class WorkflowErrorCode(str, Enum):
    CONTROLLER_NOT_INITIALIZED = "WORKFLOW_CONTROLLER_NOT_INITIALIZED"
    WORKFLOW_DIRECTORY_NOT_SET = "WORKFLOW_DIRECTORY_NOT_SET"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    INVALID_FOLDER_NAME = "WORKFLOW_INVALID_FOLDER_NAME"
    FOLDER_ALREADY_EXISTS = "WORKFLOW_FOLDER_ALREADY_EXISTS"
    PARENT_FOLDER_NOT_FOUND = "WORKFLOW_PARENT_FOLDER_NOT_FOUND"
    FOLDER_ALREADY_EXISTS_SAME_NAME = "WORKFLOW_FOLDER_ALREADY_EXISTS_SAME_NAME"
    FOLDER_NOT_EMPTY = "WORKFLOW_FOLDER_NOT_EMPTY"
    METADATA_NOT_FOUND = "WORKFLOW_METADATA_NOT_FOUND"
    INVALID_PREVIEW_INDEX = "WORKFLOW_INVALID_PREVIEW_INDEX"
    IMAGE_DIRECTORY_NOT_SET = "WORKFLOW_IMAGE_DIRECTORY_NOT_SET"
    INVALID_FOLDER_ID = "WORKFLOW_INVALID_FOLDER_ID"
    NO_UPDATES_PROVIDED = "WORKFLOW_NO_UPDATES_PROVIDED"
    FOLDER_NOT_FOUND_IN_FILESYSTEM = "WORKFLOW_FOLDER_NOT_FOUND_IN_FILESYSTEM"
    TARGET_LOCATION_EXISTS = "WORKFLOW_TARGET_LOCATION_EXISTS"
    FOLDER_NOT_FOUND = "WORKFLOW_FOLDER_NOT_FOUND"
    MOVE_WORKFLOW_FAILED = "WORKFLOW_MOVE_FAILED"
    DELETE_WORKFLOW_FAILED = "WORKFLOW_DELETE_FAILED"
    UPLOAD_PREVIEW_FAILED = "WORKFLOW_UPLOAD_PREVIEW_FAILED"
    DELETE_PREVIEW_FAILED = "WORKFLOW_DELETE_PREVIEW_FAILED"
